export { default as PersonalCenter } from './personal-center.vue';
export { default as MyInformation } from './information.vue';
export { default as Password } from './password.vue';
export { default as TransactionPwd } from './transaction-pwd.vue';
export { default as BindPhone } from './bind-phone.vue';
export { default as Address } from './address.vue';
export { default as Voucher } from './voucher.vue';
export { default as AuthInfo } from './auth-info.vue';
export { default as DevelopCommission } from './develop-commission.vue';
